// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using exam_back.DB;

#nullable disable

namespace examback.Migrations
{
    [DbContext(typeof(DentistDbContext))]
    [Migration("20221209071341_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("exam_back.Models.MedicalHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VisitTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalHistory");
                });

            modelBuilder.Entity("exam_back.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6b09813-f15d-419f-8747-10c304258091"),
                            Birthday = new DateTime(2003, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mykhailo",
                            Surname = "Vovkanych"
                        },
                        new
                        {
                            Id = new Guid("76d4dab5-9b77-4d97-8ef1-ea1380a405b1"),
                            Birthday = new DateTime(2002, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Taras",
                            Surname = "Shevchenko"
                        },
                        new
                        {
                            Id = new Guid("98b66e0f-0396-401a-8d72-d7d36d25be50"),
                            Birthday = new DateTime(1994, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Stepan",
                            Surname = "Bandera"
                        },
                        new
                        {
                            Id = new Guid("e9ced0b5-f079-4094-83a7-90347f211423"),
                            Birthday = new DateTime(1982, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lesia",
                            Surname = "Ukrainka"
                        });
                });

            modelBuilder.Entity("exam_back.Models.MedicalHistory", b =>
                {
                    b.HasOne("exam_back.Models.Patient", "Patient")
                        .WithMany("History")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("exam_back.Models.Patient", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
